#!/usr/bin/env python3
"""Emit web/animations.js: animation NAMES and loop ranges already in this repo.

Names come from the pinned libsm64 header, loop ranges from the timing table
that tools/import_kinematics.py generated. No pose, model, texture, or audio
data is read or produced here; the renderer only needs to know which animation
the core selected and how far through its loop the current frame sits.

Usage: python3 tools/export_animations.py
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
IDS = ROOT / "vendor/libsm64/src/decomp/include/mario_animation_ids.h"
TIMING = ROOT / "core/kinematics.inc.h"
OUTPUT = ROOT / "web/animations.js"


def generate():
    header = re.sub(r"/\*.*?\*/|//[^\n]*", "", IDS.read_text(), flags=re.S)
    body = re.search(r"enum MarioAnimID\s*\{(.*?)\}", header, re.S).group(1)
    names = [name.strip().removeprefix("MARIO_ANIM_")
             for name in body.split(",") if name.strip()]
    rows = re.findall(r"^\s*\{([-\d,]+),0,root_\d+,index_\d+,0\},$", TIMING.read_text(), re.M)
    loops = [[int(v) for v in row.split(",")][3:5] for row in rows]
    if len(names) != len(loops):
        raise SystemExit(f"{len(names)} animation names but {len(loops)} timing records")
    lines = ["// Generated by tools/export_animations.py. DO NOT EDIT.",
             "// Animation identity and loop range only; no skeletal pose data.",
             "// [name, loopStart, loopEnd] indexed by the core's animation id.",
             "export const animations = ["]
    lines += [f"  ['{name}',{start},{end}]," for name, (start, end) in zip(names, loops)]
    lines += ["];", "",
              "export function animationName(id) { return animations[id]?.[0] ?? 'UNKNOWN'; }", "",
              "// Position inside the loop, 0 to 1, matching geo_update_animation_frame.",
              "export function animationPhase(id, frame) {",
              "  const entry = animations[id];",
              "  if (!entry) return 0;",
              "  const [, start, end] = entry;",
              "  const span = Math.max(1, end - start);",
              "  return Math.min(1, Math.max(0, (frame - start) / span));",
              "}", ""]
    OUTPUT.write_text("\n".join(lines))
    print(f"Generated {len(names)} animation records in {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    generate()
