#!/usr/bin/env python3
"""Extract ONLY action timing and XYZ root displacement from public decomp C.

No ROM reader, skeletal pose, model, texture, or audio import exists here.
Usage: python3 tools/import_kinematics.py /path/to/n64decomp/sm64
"""
import argparse
from export_animations import generate as export_animation_metadata
from pathlib import Path
import re
import subprocess

ROOT = Path(__file__).resolve().parents[1]
PIN = "9921382a68bb0c865e5e45eb594d9c64db59b1af"


def generate(source):
    revision = subprocess.check_output(["git", "-C", str(source), "rev-parse", "HEAD"], text=True).strip()
    if revision != PIN:
        raise SystemExit(f"Expected decomp revision {PIN}, got {revision}")
    if subprocess.check_output(["git", "-C", str(source), "status", "--porcelain", "--", "assets/anims"], text=True).strip():
        raise SystemExit("Animation source has local changes; use the clean pinned revision")
    entries = {}
    for path in sorted((source / "assets/anims").glob("*.inc.c")):
        code = re.sub(r"/\*.*?\*/|//[^\n]*", "", path.read_text(), flags=re.S)
        arrays = {}
        for name, body in re.findall(r"static const [us]16 (\w+)\[\] = \{(.*?)\};", code, re.S):
            arrays[name] = [int(v.strip(), 0) for v in body.split(",") if v.strip()]
        for name, body in re.findall(r"static const struct Animation (anim_[0-9A-F]+)\[\] = \{(.*?)\};", code, re.S):
            fields = [v.strip() for v in body.split(",") if v.strip()]
            metadata = [int(v, 0) for v in fields[:5]]
            values, indices = arrays[fields[6]], arrays[fields[7]]
            root, root_indices = [], []
            for axis in range(3):
                count, offset = indices[axis * 2:axis * 2 + 2]
                root_indices.extend([count, len(root)])
                root.extend(v if v < 32768 else v - 65536 for v in values[offset:offset + count])
            entries[int(name[5:], 16)] = (metadata, root, root_indices)
    assert sorted(entries) == list(range(209)), "Unexpected upstream animation IDs"
    lines = ["/* Generated by tools/import_kinematics.py. DO NOT EDIT.",
             f" * n64decomp/sm64 @ {PIN}",
             " * Action timing + root XYZ displacement only; no skeletal pose data. */"]
    for i, (_, values, indices) in sorted(entries.items()):
        lines += [f"static s16 root_{i}[] = {{{','.join(map(str, values))}}};",
                  f"static u16 index_{i}[] = {{{','.join(map(str, indices))}}};"]
    lines.append("static struct Animation kinematics[209] = {")
    for i, (meta, _, _) in sorted(entries.items()):
        lines.append("    {" + ",".join(map(str, meta)) + f",0,root_{i},index_{i},0" + "},")
    lines.append("};\n")
    (ROOT / "core/kinematics.inc.h").write_text("\n".join(lines))
    export_animation_metadata()
    print(f"Generated {len(entries)} timing/root-motion records")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path)
    generate(parser.parse_args().source)
